// import localFont from "next/font/local";
import "@/app/globals.css";
import NavbarAdmin from "@/components/NavbarAdmin"
// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
 
      <div
        className={`antialiased bg-gray-100 `}
      >
        <NavbarAdmin></NavbarAdmin>
        {children}
      </div>
   
  );
}
